---
title: "Ayudantia 2"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Analisis Exploratorio de Datos 

```{r cargar datos}
library(quanteda)
library(dplyr)
library(tidyverse)
library(utf8)
library(ggplot2)

setwd("D:/Users/Italo/Documents/Italo Felipe/UAI/Semestre 11/Ayudantia Mineria de Datos/Datos")
primer_tiempo2020 <- read_csv("Primer_Tiempo2020.csv", col_names = TRUE)

#str(primer_tiempo2020)
#attach(primer_tiempo2020)
summary(primer_tiempo2020)
```
## Borrar Datos Char
```{r}
primer_tiempo2020 <- primer_tiempo2020[,!(colnames(primer_tiempo2020) %in% c("id_partido", "fasepartido", "local", "tiempo", "formationUsed
", "torneo"))]
```



## Filtrar Datos
```{r}
huachipato <- filter(primer_tiempo, equipo == "Huachipato")
```

## Graficos
```{r}
pases_hua <- huachipato$accuratePass
huachipato2 <- huachipato[order(huachipato$accuratePass),]

dotchart(huachipato$totalPass, labels = huachipato$partido, cex=0.5, xlab = "Pases", ylab = "Partido")

dotchart(huachipato$totalPass, labels = utf8_encode(huachipato$partido), cex=0.5, xlab = "Pases", ylab = "Partido")
dotchart(huachipato$accuratePass, labels = utf8_encode(huachipato$partido), cex=0.5, xlab = "Pases", ylab = "Partido")
dotchart(huachipato2$totalPass, labels = utf8_encode(huachipato$partido), cex=0.5, xlab = "Pases", ylab = "Partido")
dotchart(huachipato2$accuratePass, labels = utf8_encode(huachipato$partido), main="Pases Acertados Huachipato", pch = 16, col=c("darkblue","dodgerblue"),lcolor="gray90", cex=0.5, xlab = "Pases", ylab = "Partido", cex.main=2,cex.lab=1.5)
```


## Analisis descriptivo

```{r}
fh2020 <- primer_tiempo2020[order(primer_tiempo2020$accuratePass, decreasing = TRUE),]
fh2020

max_tiros_fuera <- max(huachipato$shotOffTarget)
max_tiros_fuera
```
## Sub DataFrames

```{r}
fh2020_pases = fh2020[,colnames(primer_tiempo2020) %in% c("equipo", "partido", "accuratePass", "totalPass", "precision_pases")]
fh2020_pases = fh2020_pases[order(fh2020_pases$precision_pases, decreasing = TRUE),]

fh2020_pases
```



## Analisis de Texto

```{r analisis texto}
team <- primer_tiempo2020$partido
team <- char_tolower(team)
team <- iconv(team, to = "ASCII//TRANSLIT")

a <- dfm(team, remove = c(stopwords("es"), "vs"))
dim(a)
```

